name: bayes
channels:
  - conda-forge
dependencies:
  - python<3.11
  - ipython>=8.6
  - jupyter>=1.0.0
  - ipympl>=0.9.2
  - pymc==5.15.1
  - seaborn>=0.12.1
  - arviz==0.18.0
  - pip>=22.3.1
  - python-graphviz
  - pip:
    - preliz==0.7.0

